/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : PWM_BL.c
**     Project     : MechGauge
**     Processor   : MC9S12ZVH128VLL
**     Component   : PWM
**     Version     : Component 02.243, Driver 01.17, CPU db: 3.00.000
**     Compiler    : CodeWarrior HCS12Z C Compiler
**     Date/Time   : 2019-12-29, 20:34, # CodeGen: 15
**     Abstract    :
**         This component implements a pulse-width modulation generator
**         that generates signal with variable duty and fixed cycle. 
**     Settings    :
**         Used output pin             : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       33            |  PA7_PWM6_FP7
**             ----------------------------------------------------
**
**         Timer name                  : PWM6 [8-bit]
**         Counter                     : PWMCNT6   [0x0492]
**         Mode register               : PWMCTL    [0x0485]
**         Run register                : PWME      [0x0480]
**         Prescaler                   : PWMPRCLK  [0x0483]
**         Compare 1 register          : PWMPER6   [0x049A]
**         Compare 2 register          : PWMDTY6   [0x04A2]
**         Flip-flop 1 register        : PWMPOL    [0x0481]
**
**         User handling procedure     : not specified
**
**         Output pin
**
**         Port name                   : A
**         Bit number (in port)        : 7
**         Bit mask of the port        : 0x0080
**         Port data register          : PTA       [0x0220]
**         Port control register       : DDRA      [0x0224]
**
**         Runtime setting period      : none
**         Runtime setting ratio       : calculated
**         Initialization:
**              Aligned                : Left
**              Output level           : high
**              Timer                  : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 3000000 Hz
**           Initial value of            period        pulse width (ratio 0%)
**             Xtal ticks              : 1000          0
**             microseconds            : 83            0
**             seconds (real)          : 0.000083333333 0.0
**
**     Contents    :
**         SetRatio8 - byte PWM_BL_SetRatio8(byte Ratio);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PWM_BL.c
** @version 01.17
** @brief
**         This component implements a pulse-width modulation generator
**         that generates signal with variable duty and fixed cycle. 
*/         
/*!
**  @addtogroup PWM_BL_module PWM_BL module documentation
**  @{
*/         


/* MODULE PWM_BL. */

#include "PWM_BL.h"

#pragma DATA_SEG PWM_BL_DATA           /* Select data segment "PWM_BL_DATA" */

#pragma CODE_SEG PWM_BL_CODE

static word RatioStore;                /* Ratio of L-level to H-level */


/*
** ===================================================================
**     Method      :  SetRatio (component PWM)
**
**     Description :
**         The method reconfigures the compare and modulo registers of 
**         the peripheral(s) when the speed mode changes. The method is 
**         called automatically as a part of the component 
**         SetHigh/SetLow/SetSlow methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void SetRatio(void)
{
  PWMDTY6 = (byte)(((0xFAUL * (dword)RatioStore) + 0x8000UL) >> 0x10U); /* Calculate new value according to the given ratio */
}

/*
** ===================================================================
**     Method      :  PWM_BL_SetRatio8 (component PWM)
**     Description :
**         This method sets a new duty-cycle ratio. The ratio is
**         expressed as an 8-bit unsigned integer number. Value 0 - 255
**         is proportional to ratio 0 - 100%. 
**         Note: Calculated duty depends on the timer possibilities and
**         on the selected period.
**         The method is available only if method <SetPeriodMode> is
**         not selected.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Ratio           - Ratio to set. 0 - 255 value is
**                           proportional to ratio 0 - 100%
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte PWM_BL_SetRatio8(byte Ratio)
{
  RatioStore = (((word)Ratio << 8U) + 0x80U); /* Store new value of the ratio */
  SetRatio();                          /* Calculate and set up new appropriate values of the duty and period registers */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  PWM_BL_Init (component PWM)
**
**     Description :
**         Initializes the associated peripheral(s) and the component's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PWM_BL_Init(void)
{
  /* PWMCNT6: PWMCNT6=0 */
  setReg8(PWMCNT6, 0x00U);             /* Reset Counter */ 
  RatioStore = 0x00U;                  /* Store initial value of the ratio */
  /* PWMDTY6: PWMDTY6=0 */
  setReg8(PWMDTY6, 0x00U);             /* Store initial value to the duty-compare register */ 
  /* PWMPER6: PWMPER6=0xFA */
  setReg8(PWMPER6, 0xFAU);             /* and to the period register */ 
  /* PWMPRCLK: ??=0,PCKB2=0,PCKB1=0,PCKB0=0,??=0,PCKA2=0,PCKA1=0,PCKA0=0 */
  setReg8(PWMPRCLK, 0x00U);            /* Set prescaler register */ 
  /* PWMSCLB: BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=1,BIT1=0,BIT0=0 */
  setReg8(PWMSCLB, 0x04U);             /* Set scale register */ 
  /* PWMCLK: PCLK6=1 */
  setReg8Bits(PWMCLK, 0x40U);          /* Select clock source */ 
  /* PWME: PWME6=1 */
  setReg8Bits(PWME, 0x40U);            /* Run counter */ 
}

/* END PWM_BL. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS12Z series of microcontrollers.
**
** ###################################################################
*/
