/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : PWM_WL.h
**     Project     : MechGauge
**     Processor   : MC9S12ZVH128VLL
**     Component   : PWM
**     Version     : Component 02.243, Driver 01.17, CPU db: 3.00.000
**     Compiler    : CodeWarrior HCS12Z C Compiler
**     Date/Time   : 2019-12-29, 20:34, # CodeGen: 15
**     Abstract    :
**         This component implements a pulse-width modulation generator
**         that generates signal with variable duty and fixed cycle. 
**     Settings    :
**         Used output pin             : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       34            |  PA6_PWM4_FP6
**             ----------------------------------------------------
**
**         Timer name                  : PWM4 [8-bit]
**         Counter                     : PWMCNT4   [0x0490]
**         Mode register               : PWMCTL    [0x0485]
**         Run register                : PWME      [0x0480]
**         Prescaler                   : PWMPRCLK  [0x0483]
**         Compare 1 register          : PWMPER4   [0x0498]
**         Compare 2 register          : PWMDTY4   [0x04A0]
**         Flip-flop 1 register        : PWMPOL    [0x0481]
**
**         User handling procedure     : not specified
**
**         Output pin
**
**         Port name                   : A
**         Bit number (in port)        : 6
**         Bit mask of the port        : 0x0040
**         Port data register          : PTA       [0x0220]
**         Port control register       : DDRA      [0x0224]
**
**         Runtime setting period      : none
**         Runtime setting ratio       : calculated
**         Initialization:
**              Aligned                : Left
**              Output level           : high
**              Timer                  : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 3000000 Hz
**           Initial value of            period        pulse width (ratio 0%)
**             Xtal ticks              : 1000          0
**             microseconds            : 83            0
**             seconds (real)          : 0.000083333333 0.0
**
**     Contents    :
**         SetRatio8 - byte PWM_WL_SetRatio8(byte Ratio);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PWM_WL.h
** @version 01.17
** @brief
**         This component implements a pulse-width modulation generator
**         that generates signal with variable duty and fixed cycle. 
*/         
/*!
**  @addtogroup PWM_WL_module PWM_WL module documentation
**  @{
*/         

#ifndef __PWM_WL
#define __PWM_WL

/* MODULE PWM_WL. */

#include "Cpu.h"

#pragma CODE_SEG PWM_WL_CODE

#define PWM_WL_PERIOD_VALUE  0xFAUL    /* Initial period value in ticks of the timer */
#define PWM_WL_PERIOD_VALUE_HIGH 0xFAUL /* Initial period value in ticks of the timer in high speed mode */

byte PWM_WL_SetRatio8(byte Ratio);
/*
** ===================================================================
**     Method      :  PWM_WL_SetRatio8 (component PWM)
**     Description :
**         This method sets a new duty-cycle ratio. The ratio is
**         expressed as an 8-bit unsigned integer number. Value 0 - 255
**         is proportional to ratio 0 - 100%. 
**         Note: Calculated duty depends on the timer possibilities and
**         on the selected period.
**         The method is available only if method <SetPeriodMode> is
**         not selected.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Ratio           - Ratio to set. 0 - 255 value is
**                           proportional to ratio 0 - 100%
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

void PWM_WL_Init(void);
/*
** ===================================================================
**     Method      :  PWM_WL_Init (component PWM)
**
**     Description :
**         Initializes the associated peripheral(s) and the component's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma CODE_SEG DEFAULT

/* END PWM_WL. */

#endif /* ifndef __PWM_WL */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS12Z series of microcontrollers.
**
** ###################################################################
*/
